### ISSUE TITLE
Detailed Documentation

### ISSUE THREAD

**Issue by SylarRuby** [thallium205/xero#12]
Hi

I'm a newbie web developer and I am a bit stuck. Consumer Secret/Key are easily to drop in as I grab those from the xero application. I am lost with the rsa_private_key. I have done some search and found how to generate the rsa key. Do that and uploaded to xero application. But what next? Where is this RSA_PRIVATE_KEY?

**Comment by andrew-wharton** [comment]
Yep, the README is terse, to say the least.

You need to pass in the RSA_PRIVATE_KEY as a String, so how you you get it into your application is up to you. Normally it's loaded into the application at runtime just like other configuration such as database credentials etc. However you do it, just don't put it as a String in your application code and check it into your SCM...

If you're on a *nix system, the private part of the key is most likely in your ~/.ssh directory and called "id_rsa" or something similar. If you're on Windows, I've no idea where it is...

**Comment by SylarRuby** [comment]
hi.

i have the privatekey.pem but how to pass that as a string?

**Comment by andrew-wharton** [comment]
So the content of that file is just text (you can look at it with any text editor) and you need to get this text into your application as a String. Once you have it stored in a variable (or constant) as a String, you can pass it to the Xero constructor function, just like any other variable.

How to get configuration data like this into a node application isn't specific to this Xero library, so I'd head over to Stackoverflow to get help with this. If you're using a framework, then it's likely that there's a standard way of passing/setting configuration data in your app. Otherwise, you could set the location of the file as an environment variable and read the file as a String using that environment variable. See these links for details.

- https://nodejs.org/api/process.html#process_process_env
- https://nodejs.org/api/fs.html#fs_fs_readfile_filename_options_callback

**Comment by andrew-wharton** [comment]
@SylarRuby If you have any suggestions about helpful info that could/should be in the README, feel free to send these proposed edits in a pull request.
