### ISSUE TITLE
Example in readme is confusing

### ISSUE THREAD

**Issue by tomaskulich** [thallium205/xero#17]
``` javscript
var Xero = require('xero');

var xero = new Xero(CONSUMER_KEY, CONSUMER_SECRET, RSA_PRIVATE_KEY);
xero.call('GET', '/Users', null, function(err, json) {
        if (err) {
            log.error(err);
            return res.json(400, {error: 'Unable to contact Xero'});
        }
        return res.json(200, json);
    });
```

What is `res`? It's nowhere defined, probably Express's request object.

**Comment by chrisdamba** [comment]
Hi @thallium205  Is this issue still need a fix? I'm looking to gain more contributions and would like to give it a go?

**Comment by andrew-wharton** [comment]
Hi,

Yeah, you're right that the example needs improvement. 

Since this is clearly an ongoing problem for users (see https://github.com/thallium205/xero/issues/13), @chrisdamba feel free to put together a pull request. I'm happy for you to use my example in https://github.com/thallium205/xero/issues/13 if you wish or for you to tweak it if you think it could be clearer.

I'll be happy to merge it for you.

**Comment by chrisdamba** [comment]
Thanks @andrew-wharton. I've just used your example in #13, no need to tweak as the example was straightforward.

**Comment by andrew-wharton** [comment]
merged, thanks.
